language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install -r requirements-py26.txt; fi
  - pip install .

script:
  - python tests/ut/test_util.py
  - python tests/sample.py
  - python tests/integration_test/test_logtail_config.py
  - python tests/integration_test/test_entity.py
  - python tests/integration_test/test_log_handler.py
  - python tests/sample_consumer.py
